# Generated by Django 4.2 on 2023-10-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='datef',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='fname',
            new_name='full_name',
        ),
    ]
