# Generated by Django 4.2 on 2023-10-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_purpose',
            new_name='appointment_purpose',
        ),
    ]
